<?php

namespace xlerr\common\widgets;

use xlerr\common\assets\DataTableFixedColumnsAsset;
use yii\helpers\Json;
use yii\web\JsExpression;

/**
 * Class DataTable
 *
 * @package xlerr\common\widgets
 */
class DataTable extends \yii\grid\GridView
{
    public $tableOptions = [
        'class' => 'table table-striped',
        'style' => 'width: 100%',
    ];

    public $options = [
        'class' => 'box box-primary',
    ];

    public $pager = [
        'options' => [
            'class' => 'pagination pagination-sm no-margin pull-right',
        ],
    ];

    /**
     * @var array
     * @see https://datatables.net/reference/option/
     */
    public $dataTableOptions = [];

    public $dataTableEvents = [];

    public $layout = '<div class="box-header with-border">{summary}</div><div class="box-body table-responsive no-padding">{items}</div><div class="box-footer">{pager}</div>';

    public function init()
    {
        $this->dataTableOptions = array_merge([
            'paginate'  => false,
            'ordering'  => false,
            'searching' => false,
            'info'      => false,
            'scrollX'   => true,
            'scrollY'   => false,
        ], $this->dataTableOptions);

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run();

        $view = $this->getView();

        DataTableFixedColumnsAsset::register($view);

        $options = Json::htmlEncode($this->dataTableOptions);

        $id = $this->options['id'];

        $events = '';
        foreach ($this->dataTableEvents as $event => $func) {
            $events .= vsprintf("\n.on('%s', %s)", [
                $event,
                ($func instanceof JsExpression ? $func : new JsExpression($func)),
            ]);
        }

        $view->registerJs("jQuery('#$id table')$events\n.dataTable($options);");
    }
}
